package com.dingli.diandians.common;

import java.util.List;

public class Course {
	public int id;
	public String dayOfWeek;
	public String classRoom;
	public String courseName;
	public String classBeginTime;
	public String classEndTime;
	public String teach_time;
	public String weekName;
	public String whichLesson;
	public int lessonOrderNum;
	public String businessContent;
	public List<Coursecenter> classInfor;
	public String teacher;
	public int rollCallPercent;
	public int assessPeopelNum;
	public int totalPeopelNum;
	public String className;
	public List<ResultOne>  rollCallList;
	public int classSize;
	public String name;
	public String score;
	public String content;
	public String createDate;
	public int average;
	public String course;
	public String date;
	public String type;
	public int deviation;
	public String week;
	public String rollcallType;
	public String isAutomatic;
	public String localtion;
	public int scheduleId;
	public String rollCallEndTime;
	public boolean rollCall;
	public String pushTime;
	public boolean canReport;
	public boolean haveReport;
	public int lateTime;
	public String signTime;
	public String rollCallTypeOrigin;
	public String assessScore;
	public String teacherName;
	public int normal;
	public int abnormal;
	public String month;
	public List<Data> data;
	public String year;
	public String address;
	public String picUrl;
	public String title;
	public int hitCount;
	public int praiseCount;
}
